version: "3.3"

services:

  traefik:
    image: traefik:latest
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/config.yaml"
      - "--providers.file.watch=true"
      - "--accesslog=true"
      - "--accesslog.filePath=/logs/access.log"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
    networks:
      - internal
    ports:
      - ${LISTEN_PORT_HTTP}:80
      - ${LISTEN_PORT_HTTPS}:443
      - ${LISTEN_TRAEFIK_HTTP}:8080
    volumes:
      - "./traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - traefik.enable=true

  couchdb:
    build:
      context: ./couch
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.couchdb-auth.forwardauth.address=http://api:3000/api/auth/couchcheck"
      - "traefik.http.middlewares.couchdb-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.couchdb-auth.forwardauth.authResponseHeadersRegex=^X-Auth-"
      - "traefik.http.middlewares.couch-prefix.stripprefix.prefixes=/couchdb"
      - "traefik.http.middlewares.couch-prefix.stripprefix.forceSlash=false"
      - "traefik.http.routers.couchdb.tls=true"
      - "traefik.http.routers.couchdb.rule=PathPrefix(`/couchdb`)"   
      - "traefik.http.routers.couchdb.middlewares=couchdb-auth,couch-prefix"
      - "traefik.http.services.couchdb.loadbalancer.server.port=5984"
    networks:
      - internal
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - COUCHDB_SECRET=${COUCHDB_SECRET}
    volumes:
      - couch-data:/opt/couchdb/data

  api:
    build:
      context: ./api
    depends_on:
       - couchdb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"     
      - "traefik.http.services.api.loadbalancer.server.port=3000"
    environment:
      - COUCH_SECRET=${COUCHDB_SECRET}
      - COUCH_URL=http://couchdb:5984
    networks:
      - internal

  web:
    build:
      context: ./web
    depends_on:
       - couchdb
       - api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"     
      - "traefik.http.services.web.loadbalancer.server.port=80"
    networks:
      - internal

networks:
  internal:

volumes:
  couch-data:
  couch-settings: