// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise.ts';
import { OpenAPI } from './core/OpenAPI.ts';
import { request as __request } from './core/request.ts';
import type { PostApiAuthLoginData, PostApiAuthLoginResponse, PostApiAuthRefreshData, PostApiAuthRefreshResponse, GetApiAuthCheckResponse, PostApiAuthLogoutResponse, GetApiRacesResponse, PostApiRacesData, PostApiRacesResponse } from './types.gen.ts';

export class AuthService {
    /**
     * Login user using username & password
     * @param data The data for the request.
     * @param data.body
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static postApiAuthLogin(data: PostApiAuthLoginData = {}): CancelablePromise<PostApiAuthLoginResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/auth/login',
            body: data.body
        });
    }
    
    /**
     * Refresh user token
     * @param data The data for the request.
     * @param data.body
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static postApiAuthRefresh(data: PostApiAuthRefreshData = {}): CancelablePromise<PostApiAuthRefreshResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/auth/refresh',
            body: data.body
        });
    }
    
    /**
     * Check user token
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static getApiAuthCheck(): CancelablePromise<GetApiAuthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/auth/check'
        });
    }
    
    /**
     * Logout user
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static postApiAuthLogout(): CancelablePromise<PostApiAuthLogoutResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/auth/logout'
        });
    }
    
}

export class RacesService {
    /**
     * Get races
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static getApiRaces(): CancelablePromise<GetApiRacesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/races'
        });
    }
    
    /**
     * Add race
     * @param data The data for the request.
     * @param data.body
     * @returns unknown Default Response
     * @throws ApiError
     */
    public static postApiRaces(data: PostApiRacesData = {}): CancelablePromise<PostApiRacesResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/races',
            body: data.body
        });
    }
    
}