// This file is auto-generated by @hey-api/openapi-ts

export type PostApiAuthLoginData = {
    body?: {
        name: string;
        password: string;
    };
};

export type PostApiAuthLoginResponse = {
    refreshToken: string;
};

export type PostApiAuthRefreshData = {
    body?: {
        refreshToken: string;
    };
};

export type PostApiAuthRefreshResponse = {
    ok: boolean;
};

export type GetApiAuthCheckResponse = {
    name: string;
    roles: Array<(string)>;
};

export type PostApiAuthLogoutResponse = unknown;

export type GetApiRacesResponse = Array<{
    _id: string;
    _rev?: string;
    name: string;
}>;

export type PostApiRacesData = {
    body?: {
        name: string;
    };
};

export type PostApiRacesResponse = {
    _id: string;
    _rev?: string;
    name: string;
};

export type $OpenApiTs = {
    '/api/auth/login': {
        post: {
            req: {
                body?: {
                    name: string;
                    password: string;
                };
            };
            res: {
                /**
                 * Default Response
                 */
                200: {
                    refreshToken: string;
                };
            };
        };
    };
    '/api/auth/refresh': {
        post: {
            req: {
                body?: {
                    refreshToken: string;
                };
            };
            res: {
                /**
                 * Default Response
                 */
                200: {
                    ok: boolean;
                };
            };
        };
    };
    '/api/auth/check': {
        get: {
            res: {
                /**
                 * Default Response
                 */
                200: {
                    name: string;
                    roles: Array<(string)>;
                };
            };
        };
    };
    '/api/auth/logout': {
        post: {
            res: {
                /**
                 * Default Response
                 */
                200: unknown;
            };
        };
    };
    '/api/races': {
        get: {
            res: {
                /**
                 * Default Response
                 */
                200: Array<{
                    _id: string;
                    _rev?: string;
                    name: string;
                }>;
            };
        };
        post: {
            req: {
                body?: {
                    name: string;
                };
            };
            res: {
                /**
                 * Default Response
                 */
                200: {
                    _id: string;
                    _rev?: string;
                    name: string;
                };
            };
        };
    };
};